name = "neurapath-homepage"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-07-25"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[placement]
mode = "smart"

[vars]
ENVIRONMENT = "production"
