name = "neurapath-homepage"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-11-19"
minify = true
account_id = "6c2dccead5cc8b117a208576df3a8c2c"

routes = [
  { pattern = "neurapath.shop", custom_domain = true },
  { pattern = "www.neurapath.shop", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
ENVIRONMENT = "production"
PUBLIC_POSTHOG_KEY = "phc_VzmOv7NIStk1xXr2SWJIoVoUq8jhUMqRRtlnHifcF0d"
PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"