name = "neurapath-homepage"
main = ".svelte-kit/cloudflare/_worker.js"
preview_urls = false
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-08-19"
minify = true

routes = [
  { pattern = "landing.neurapath.shop", custom_domain = true },
  { pattern = "www.landing.neurapath.shop", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
NODE_VERSION = "24.6.0"
ENVIRONMENT = "production"