name = "neurapath-homepage"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-10-16"
minify = true

routes = [
  { pattern = "landing.neurapath.shop", custom_domain = true },
  { pattern = "www.landing.neurapath.shop", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
ENVIRONMENT = "production"
PUBLIC_POSTHOG_KEY = "phc_VzmOv7NIStk1xXr2SWJIoVoUq8jhUMqRRtlnHifcF0d"
PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"